base_url = "https://www.utrakr.app"
compile_sass = true
highlight_code = true
build_search_index = false

# common
title = "Î¼trakr"
description = "Your micro url creator that helps track usage."

[extra]
submit_url = "http://localhost:8080"